version: '3.8'

volumes:
  postgres-data:

networks:
  watchmap:
    driver: bridge

services:
  monitor:
    container_name: watchmap-monitor
    build:
      context: ./monitor
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    networks:
      - watchmap
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      PROJECT_HOST: http://localhost:3000
    depends_on:
      - db

  db:
    container_name: watchmap-db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - watchmap
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  express-1:
    container_name: watchmap-express-1
    build:
      context: ./servers/express-1
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    networks:
      - watchmap
    ports:
      - "3001:3001"
    depends_on:
      - monitor
    environment:
      WATCHMAP_SERVER_REGISTER_URL: http://monitor:3000/api/register
      WATCHMAP_SERVER_REQUEST_MONITOR_URL: http://monitor:3000/api/request-monitor
      WATCHMAP_SERVICE_NAME: Express-1
      PORT: 3001

  express-2:
    container_name: watchmap-express-2
    build:
      context: ./servers/express-2
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    networks:
      - watchmap
    ports:
      - "3002:3002"
    depends_on:
      - monitor
    environment:
      WATCHMAP_SERVER_REGISTER_URL: http://monitor:3000/api/register
      WATCHMAP_SERVER_REQUEST_MONITOR_URL: http://monitor:3000/api/request-monitor
      WATCHMAP_SERVICE_NAME: Express-2
      PORT: 3002

  django-1:
    container_name: watchmap-django-1
    build:
      context: ./servers/django_1
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    networks:
      - watchmap
    ports:
      - "8000:8000"
    depends_on:
      - monitor
    environment:
      WATCHMAP_SERVER_REGISTER_URL: http://monitor:3000/api/register
      WATCHMAP_SERVER_REQUEST_MONITOR_URL: http://monitor:3000/api/request-monitor
      WATCHMAP_SERVICE_NAME: Django-1
      PORT: 8000